### PR TITLE
Two New Module 

### PR DESCRIPTION
**Pull request by MariusVinaschi**
Hi, how are you? 🙂 

I made some changes to the code. 

- Respect PEP8
- Add a module for file upload 
- Add a module for Wappalyzer https://www.wappalyzer.com/

Thank you 🙂
Best regards 
Marius

### CODE REVIEW

**Comment by knassar702** [comment]
hi @MariusVinaschi, thanks for these awesome changes That’s very kind of you:)
small question, I downloaded your changes but I got an error about modules

```
~/testing/scant3r on  master! ⌚ 13:50:36
$ echo 'http://testphp.vulnweb.com/search.php' | ./scant3r.py
                          __ _____
   ______________ _____  / /|__  /_____
  / ___/ ___/ __ `/ __ \/ __//_ </ ___/
 (__  ) /__/ /_/ / / / / /____/ / /
/____/\___/\__,_/_/ /_/\__/____/_/

[!] Coded by: Khaled Nassar @knassar702
[!] Version: 0.8#Beta

[ERROR][2021-09-28,13:50:37] module_loader -> No module named 'validators'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'
[ERROR][2021-09-28,13:50:37] module_loader -> 'modules'

```
you can fix this?

best regards
@knassar702

**Comment by MariusVinaschi** [comment]
Hi, 

Sorry, I think I forgot to put _validators_ in the requirements file. I will fix that. 

Thank you, 

best regards 
@MariusVinaschi

**Comment by knassar702** [comment]
thanks, time to merge these awesome changes 

LGTM

**Comment by knassar702** [comment]
hey @MariusVinaschi, I think this issue #41  because of your last pull request can you check? (because I'm away now)

best regards

**Pull request merged**
