### PR TITLE
Structure - Clean Code - Class 

### PR DESCRIPTION
**Pull request by MariusVinaschi**
Hi ! How are you?  🙂 

Today : 

- Update the structures of modules and use the same name for all 
- Clean the code in data and add comments 
- Create a Scan class. I think it's a great idea if we have one parent class and all the modules inherit it.  
- Make some corrections in the module 
 
Thank you! 

Best regards 
Marius

### CODE REVIEW

**Comment by knassar702** [comment]
hey @MariusVinaschi  ,  Thank you for all your hard work on this :heart:

**Comment by knassar702** [comment]
@MariusVinaschi don't forget to add your github account info in your git config , for save all changes & PRS  to your github account logs and add you in to Contributors list :D 

best regards 
@knassar702

**Comment by MariusVinaschi** [comment]
No problem with pleasure !

**Comment by knassar702** [comment]
hey @MariusVinaschi  , i think all functions of `modules/scan.py` file should to add in `core/libs/all/data.py` 
because this the file of all function can use it in the modules 

if you have another opinion. tell me about it :D

**Comment by MariusVinaschi** [comment]
Hey,

 I don't think so, because Scan.py is a class, and I think all the module should inherit from this class. 

The methods from scan.py  will be accessible from all the modules. It's different from basic function 

Best regards 
Marius

**Comment by knassar702** [comment]
great idea, I'll add some functions for this class 

thanks for this idea :D

**Pull request merged**
