### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by MariusVinaschi**
Hello,

I made some changes in code. 

If you need some indications don't hesitate. 

I will try to make the code work on this vulnerable app https://dvwa.co.uk/. 

Thank you

### CODE REVIEW

**Comment by knassar702** [comment]
Thank you so much, im so happy for this awesome changes :1st_place_medal: 
* clean code and make it better :broom:  :100: 
* better user help output  :ok_hand: 
* correct `opts.yaml` file :+1: 
* add cool functions :cool: 
* remove unused functions & variables  :broom: 

Leo Clap

best regards
@knassar702

**Comment by knassar702** [comment]
> I will try to make the code work on this vulnerable app https://dvwa.co.uk/.
i think scant3r can work with this app , just add your cookies & session with `-H "Cookies: session=example"`
if you have another opinion , please tell me about it :D

**Comment by MariusVinaschi** [comment]
I put the headers correctly but it's not working. 
I will try to find the errors and make a new merged request.  
Thank you for this amazing project.

**Comment by knassar702** [comment]
use -d option for display the requests/response
if you using POST method check last commit : https://github.com/knassar702/scant3r/commit/bb44c778d4954ec04f81d73834cdfad9eb180f72
for fix post method requests with empty method

**Comment by MariusVinaschi** [comment]
Thank you I will check that !

**Pull request merged**
