### PR TITLE
Fix import Error

### PR DESCRIPTION
**Pull request by MariusVinaschi**
Hi, 

I just see an "import error" in the requester module. I add some indications in the file "module_loader". 

It's possible to create a new Dev branch on your repository, please? 

I will try to find the bug with DVWA website, so I will try to add more print to see the advancement of the task.  
Do you think it's a good idea to separate the module and script into two different folders? 
It's possible to add one parameter in the command line to execute all the modules?  

Thank you,
Best regards Marius.

### CODE REVIEW

**Comment by knassar702** [comment]
hi @MariusVinaschi , thanks for these changes :heart: 


> It's possible to create a new Dev branch on your repository, please?

why not , here [dev branch](https://github.com/knassar702/scant3r/tree/dev) 

> It's possible to add one parameter in the command line to execute all the modules?

I think it's a great idea, I'll try to add it as soon as possible :+1: 

>  Do you think it's a good idea to separate the module and script into two different folders?

Can you explain more ?

best regards
@knassar702

**Comment by MariusVinaschi** [comment]
Create one folder for the modules (All python scanners) and another folder for scripts (Js/Go scanners). (The project has only one folder for the moment: modules). I think it will add more clarity. 

Best regards
@MariusVinaschi

**Comment by knassar702** [comment]
great idea , here the commit : https://github.com/knassar702/scant3r/commit/aae9e91e00efb36fd76387d7611c8b0cc86ab785

```
├── modules
│   ├── python
 |     ├── scripts
```

**Comment by MariusVinaschi** [comment]
Thank you, so much. 
Best regards, 
Marius

**Comment by knassar702** [comment]
hi @MariusVinaschi  

>  It's possible to add one parameter in the command line to execute all the modules?

i add it now , you can find/change all modules from `conf/main_scan.yaml` file 

screenshot-RcTDWz0ikIspi


best regards
@knassar702

**Comment by MariusVinaschi** [comment]
Thank you !

**Pull request merged**
